### ISSUE TITLE
Is there a default ttl on Indexes? 

### ISSUE THREAD

**Issue by ishaan-jaff** [redis/redis-vl-python#114]
I see the index data getting cleared after about 5-10 mins, does it clear the Index after X minutes ?

**Comment by bsbodden** [comment]
AFAIK the default TTL for the cache is None, unless you explicitly set it like:
```
cache = SemanticCache(...)
...
cache.set_ttl(10) # 10 seconds 
```

**Comment by ishaan-jaff** [comment]
any idea why the data from my index might be clearing after about 5-10 mins ?

**Comment by bsbodden** [comment]
@ishaan-jaff can you share some of your code? If you are creating a SearchIndex there is also a `drop`  boolean param https://github.com/RedisVentures/redisvl/blob/8d388011c22fea168c9ed3f40c2543614d655304/redisvl/index/index.py#L386 that drops all the data associated with the index when you delete the index.

**Comment by tylerhutcherson** [comment]
This should not happen. As @bsbodden points out there are a few places where you could maybe accidentally delete the data whether its on `create()` (by overwriting) or on explicit `delete()` calls.

Can you confirm which flavor of Redis you are running? Also sample code will help us debug.  Thanks!
