### ISSUE TITLE
Improve & Enrich the LLM client implementation for TextVectorizer

### ISSUE THREAD

**Issue by pierrelambert** [redis/redis-vl-python#160]
1. There is no direct way today to use another service than the OpenAI. 
It would be nice to be able to use any service with an API compatible with the OpenAI one.
The target host seems to be hardcoded towards the Open AI service, I may want to use an on-prem/local LLM service, but as for today this is not possible.
2. Add support for mistral.ai equivalent

**Comment by justin-cechmanek** [comment]
We currently have several TextVectorizer classes to choose from [here](https://github.com/redis/redis-vl-python/tree/main/redisvl/utils/vectorize/text), but you're correct that mistral is not yet supported.
We are in the process of adding support to allow for local vectorizers in [this PR](https://github.com/redis/redis-vl-python/pull/156). Are there are other specific features you would like to see added to TextVectorizers?

**Comment by pierrelambert** [comment]
I really detected as missing the generic side of connectivity only for now

**Comment by tylerhutcherson** [comment]
Agreed -- @justin-cechmanek we should make a ticket to allow users to overrride the base_url param (and potentially others) for the OpenAI spec. Should be a simple update to the openAI text vectorizer. The support for mistral.ai would be good too given we have some customers using this.

**Comment by tylerhutcherson** [comment]
@pierrelambert FYI https://github.com/redis/redis-vl-python/pull/171 Can you verify this enables what you need? You just include base_url in the api_config object now.
