### ISSUE TITLE
IndexError: list index out of range while applying filter on semantic cache check

### ISSUE THREAD

**Issue by MeharRamzan** [redis/redis-vl-python#203]
I am facing this issue while trying to applying filter on semantic cache check
![image](https://github.com/user-attachments/assets/beef4b5d-5c3e-47cb-921b-817cd30a56e8)
![image](https://github.com/user-attachments/assets/610644df-b147-4d19-a0ec-a44f642b6344)

**Comment by tylerhutcherson** [comment]
For some reason, the result coming back from the cache check step is empty. We need steps to be able to reproduce the entire flow.

Can you clear the db and then re-initialize your `SemanticCache` and then use the `private_cache.store(...)` command to populate the entry in the cache?

**Comment by MeharRamzan** [comment]
hey @tylerhutcherson, I emptied the Redis database and tried running the code again. The data is successfully stored in Redis, but there's an issue during retrieval.


![image](https://github.com/user-attachments/assets/d57dc3a4-fae4-4152-9a13-731403d77767)
![image](https://github.com/user-attachments/assets/3b957f50-ee23-415c-a89f-97efa29dbf84)

**Comment by tylerhutcherson** [comment]
We're taking a closer look, thanks!

**Comment by justin-cechmanek** [comment]
Hi. Can you share with us your redis version, redisvl version, client versions, python version?
I see your code snippets also have some lines above not shown. Is there anything there that may be influence caching?

**Comment by MeharRamzan** [comment]
@justin-cechmanek 

redis==5.0.8
redisvl==0.3.0
python==3.10.14

here is the complete code.
![image](https://github.com/user-attachments/assets/2e333d8f-2ac5-430b-84b4-c6590ae80220)

**Comment by justin-cechmanek** [comment]
We're having trouble reproducing your error. Can you confirm your 'redis_url' matches what is shown if you print `private_cache._index.client`, specifically the host and port names? My suspicion currently is that your dotenv setup is different than mine.

**Comment by tylerhutcherson** [comment]
> We're having trouble reproducing your error. Can you confirm your 'redis_url' matches what is shown if you print `private_cache._index.client`, specifically the host and port names? My suspicion currently is that your dotenv setup is different than mine.

also please validate which distribution of redis you are using?
https://redis.io/docs/latest/operate/oss_and_stack/install/install-stack/docker/

**Comment by MeharRamzan** [comment]
@justin-cechmanek here is the output of `print(private_cache._index.client)`

<redis.client.Redis(<redis.connection.ConnectionPool(<redis.connection.Connection(host=redis-14645.c275.us-east-1-4.ec2.redns.redis-cloud.com,port=14645,db=0)>)>)>

**Comment by MeharRamzan** [comment]
@tylerhutcherson I'm new to Redis and still getting familiar with its features. I've recently read the documentation [here](https://www.redisvl.com/user_guide/llmcache_03.html), signed up for Redis Cloud, created a database and Redis URL, and installed RedisInsight to monitor and manage my setup.

Everything is working well for semantic search, but I'm encountering an issue when applying specific filters. I’m running this on an Ubuntu .

**Comment by justin-cechmanek** [comment]
Are you only seeing errors when working with specific filters, or do all cache checks fail to return results?

**Comment by MeharRamzan** [comment]
@justin-cechmanek  When I use the filters, I get an error, but without the filter, it works perfectly fine. You can see in the picture that I commented out the filter_expression, and it starts working.
![image](https://github.com/user-attachments/assets/8b0ba8be-e2f6-4263-9c10-96c81d183fc0)

**Comment by tylerhutcherson** [comment]
@MeharRamzan My theory is that there is an index with the name `private_cache` that is old. Because you see:
```
11:54:53 redisvl.index.index INFO   Index already exists, not overwriting.
```
^^ That means the index is already configured in Redis (potentially, at some point without the filter field). And thus, it's not overwriting it since it's trying to use the same name `private_cache`.

To confirm, try **either**:
- Run the same example using a different `name` arg to the `SemanticCache`.
- Drop the **existing** index using `private_cache.delete()` OR by running `flushall` on your dev database (you can do this in the console in RedisInsight).

**Comment by MeharRamzan** [comment]
@tylerhutcherson  I tried it again with a new database. I deleted the old one and then tried, and now it is working.
![image](https://github.com/user-attachments/assets/47710134-cacc-49e8-9127-24c302a80af0)
