### ISSUE TITLE
"ModuleNotFoundError: No module named 'scripts'" due to overriding the 'mypy' entry point

### ISSUE THREAD

**Issue by AlirezaRoshanzamir** [redis/redis-vl-python#238]
When installing the **redisvl** library, either directly or indirectly through dependencies like **langchain-redis**, the first-party `mypy` entry point (which we use for type-checking our Python code) gets overridden by your `scripts:mypy` entry point:
![image](https://github.com/user-attachments/assets/2e1beada-2a30-491e-8a56-fcbdd2fcf520)

Which raises an error when we try to run `mypy` in our CI:
![image](https://github.com/user-attachments/assets/36013d3f-125c-4b7e-b4a4-5977250148d6)

Your revised version is quite clear! Here’s a minor tweak to make it even more concise:

However, the issue is inconsistent and difficult to reproduce. It took me an entire day to identify the root cause, as it only occurred in our CI Docker runner. The problem arises because **redisvl** is usually installed after **mypy** in our CI (when using a lockfile).

**Comment by AlirezaRoshanzamir** [comment]
My current workaround is to use the module syntax "python -m mypy" for running mypy.

**Comment by rbs333** [comment]
@AlirezaRoshanzamir thanks for the input! After touching base with the team it seems we should rename or script to help avoid this collision. We have made the following pr for this https://github.com/redis/redis-vl-python/pull/245.
